sudo: required
language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.4
      jdk: oraclejdk11

install:
  - ./.travis/install-travis-gcc.sh
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then apt install swig -y ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null  && brew install swig && brew install gimme; fi
  - eval "$(gimme 1.11)"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - make configure
  - make build-libc
  - make build-swig
  - make build-libjava
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
