language: java

matrix:
  include:
   - os: linux
     jdk: openjdk8
   - os: linux
     jdk: openjdk9
   - os: linux
     jdk: openjdk10
   - os: linux
     jdk: openjdk11
   - os: linux
     jdk: openjdk12
   - os: osx
     osx_image: xcode8.3
     jdk: oraclejdk8
   - os: osx
     osx_image: xcode8.3
     jdk: openjdk9
   - os: osx
     osx_image: xcode8.3
     jdk: openjdk10
   - os: osx
     osx_image: xcode8.3
     jdk: oraclejdk11
   - os: osx
     osx_image: xcode8.3
     jdk: openjdk12

before_install:
  - npm config delete prefix

install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi
  - cd $TRAVIS_BUILD_DIR
  - eval "$(gimme 1.11)"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
