language: java

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8


install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi  
  - cd $TRAVIS_BUILD_DIR
  - eval "$(gimme 1.11)"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - make configure
  - make build-libc
  - make build-swig
  - make build-libjava
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
