language: java

install:
  - eval "$(gimme 1.11)"
  - go version
  - mkdir swig_build && cd swig_build && wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && cd swig-3.0.12 && sudo ./configure --prefix=/usr && sudo make && sudo make install && cd ../../ && sudo rm -rf swig_build	

jdk: openjdk8
script:
  - jdk_switcher use openjdk8
  - # do stuff with OpenJDK 8
  - export JAVA_HOME=$HOME/openjdk8
  - make configure
  - make build-libc
  - make build-swig
  - make build-libjava
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
